language: android
jdk: oraclejdk8
android:
  components:
      - tools
      - platform-tools
      - tools

      - android-26
      
      - build-tools-27.0.2
script:
  # By default Travis-ci executes './gradlew build connectedCheck' if no 'script:' section found.
  - ./gradlew build
